# -*- coding: utf-8 -*-
"""clientetcp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbI8NMTeqWbIfSFpByhHcLZbav3SbcLL

Segurança de Informação com Python 
Desenvolvimento de um cliente TCP
Digital Innovation One - Instrutor Bruno Dias
Aluna: Mirian Ajiki Molicawa
"""

#importação da biblioteca socket para realização do relacionamento entre a placa de rede e o sistema operacional
import socket

#biblioteca sys fornece o acesso a algumas variáveis e funções que tem forte interação com o interpretador python
import sys

#nesta função tentar-se-á conexão com o TCP
def main():
  try:
    s= socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
  except socket.error as e:
    print('A conexão falhou!')
    print('Erro: {}'.format(e))
    sys.exit()
  print('Socket criado com sucesso') 

  HostAlvo = input('Digite o Host ou IP a ser conectado: ')
  PortaAlvo = input('Digite a porta a ser conectada: ')

  try:
     s.connect((HostAlvo, int(PortaAlvo)))
     print('Cliente TCP conectado com sucesso no Host: ' + HostAlvo + 'e na porta' + PortaAlvo)
     s.shutdown(2)
  except socket.error as e:
    print('Não foi possível conectar no Host: ' + HostAlvo +' e na porta: ' + PortaAlvo)
    print('Erro: {}'.format(e))
    sys.exit()
  if __name__ == '__main__':
   main()