# -*- coding: utf-8 -*-
"""clienteUDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18-sFKUoAuSa7oyLRMVutMA_UGqDcnhGZ
"""

#importação da biblioteca socket para realização do relacionamento entre a placa de rede e o sistema operacional
# conexão UDP para contemplar o princípio da disponibilidade - protocolo de datagrama do usuario ipv4
import socket

# criação do objeto s para receber o objeto socket.
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
print('Socket criado com sucesso...!') 
host = 'localhost'
porta = 5433
mensagem = ' Olá, servidor!'
try:
    print('Cliente:' + mensagem)
    s.sendto(mensagem.encode(), (host, 5432))
    #criação de variáveis para recebimento
    dados, servidor = s.recvfrom(4096)
    dados = dados.decode()
    print('cliente: ' + dados)
finally:
    print('Cliente: Fechando a conexão')
    s.close()