# -*- coding: utf-8 -*-
"""servidorUDP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uJS4hzZsuQpDn8hB6_ejGkoCuH6nX0HP
"""

#Importação de biblioteca
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
print('Socket criado com sucesso!') 

host = 'localhost'
port = 5432
#bind faz a ligação entre o cliente e servidor através do host e da porta
s.bind((host, port))
mensagem = '\nServidor: Olá, cliente! Tudo bem?'

#Enquanto verdadeiro envia a mensagem 4096 bytes
while 1:
  dados, endereco = s.recvfrom(4096)
  if dados:
   print('Servidor enviando mensagem...')  
   s.sendto(dados + (mensagem.encode()), endereco)